name: Conditions
on: push
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${RUN_ID}"
              if: ${{ contains(github.run_id, '1') }}
              env:
                RUN_ID: ${{ github.run_id }}
