name: Literals

on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - env:
          HTML_URL: ${{ github.event.*.html_url }}
      - run: echo "${HTML_URL}"
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 123 }}
          LITERAL_STRING: ${{ 'Hello, World' }}
          LITERAL_OMIT_STRING: World
    